package br.com.dojot.mutualauthentication.kerberosintegration.utils;

public interface KerberosIntegrationExceptionConstants {
	
	// Error constants
	String KERBEROS_INTEGRATION_ENCRYPT_TIMEOUT = "000001";
	String KERBEROS_INTEGRATION_ENCRYPT_CC_TIMEOUT = "000002";
	String KERBEROS_INTEGRATION_DECRYPT_TIMEOUT = "000003";
	String KERBEROS_INTEGRATION_DECRYPT_CC_TIMEOUT = "000004";
	String KERBEROS_INTEGRATION_REGISTER_CRYPTO_CHANNEL_TIMEOUT = "000005";
	String KERBEROS_INTEGRATION_UNREGISTER_CRYPTO_CHANNEL_TIMEOUT = "000006";
	String KERBEROS_INTEGRATION_SAVE_CRYPTO_CHANNEL_TIMEOUT = "000007";
	String KERBEROS_INTEGRATION_NUMBER_COMPONENTS_TIMEOUT = "000008";
}